# Generated by Django 4.2.14 on 2024-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fishing',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='fishing',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=300),
        ),
        migrations.AddIndex(
            model_name='fishing',
            index=models.Index(fields=['-time_create'], name='fishing_fis_time_cr_e2c1e5_idx'),
        ),
    ]
