# Generated by Django 4.2.14 on 2024-08-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_alter_fishing_options_fishing_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishing',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
